/******************************************************************************


  功能描述   : 子消息类型枚举定义
  

******************************************************************************/

typedef enum {
		/*主控收到vwas的消息的子消息类型*/
		VWAS_SUBMSG_REGION_BASE = 0x00006001,
		VWAS_CMD_GET_PROTOCOL_VER,
		VWAS_CMD_ACK_PROTOCOL_VER,
		VWAS_CMD_NETWORK_STATUS,
		VWAS_CMD_NETWORK_CONFIG,
		VWAS_IN_SLOT_QUERY,
		VWAS_HARDWARE_VERSION,
		VWAS_SOFTWARE_VERSION,
		VWAS_SYS_POWER_STATUS,
		VWAS_SYS_FAN_STATUS,
		VWAS_ALARM_DETECT,
		VWAS_ALARM_REPORT,
		VWAS_QUERY_DEV_DATE,
		VWAS_SET_DEV_DATE,
		VWAS_PREVIEW_OPEN,
		VWAS_PREVIEW_CLOSE,
		VWAS_DIGIT_DESKTOP_OPEN,
		VWAS_DIGIT_DESKTOP_CLOSE,
		VWAS_WINDOW_LOGIC_WIN_OPEN,
		VWAS_WINDOW_LOGIC_WIN_CLOSE,
		VWAS_BACKGROUND_SELECT,
		VWAS_CAPTURE_WHOLE_SCREEN,
		VWAS_CAPTURE_MULTI_FRAME,
		VWAS_WINDOW_LOGIC_WIN_REMOVE,
		VWAS_QUERY_VIDEO_IN_CFG,
		VWAS_QUERY_OUTPUT_CFG,
		VWAS_WINDOW_SIZE_CHANGE,
		VWAS_GET_LOGIC_WIN_ATTR,
		VWAS_SET_LOGIC_WIN_ATTR,
		VWAS_SELECT_LOGIC_WIN,
		VWAS_UPGRADE_BEGIN,
		VWAS_UPGRADE_END,
		VWAS_UPGRADE_PROCESSING,
		VWAS_UPGRADE_CANCEL,
		VWAS_DESKTOP_COLOR_KEY_ENABLE,
		VWAS_DESKTOP_COLOR_KEY_DISABLE,
		

		/*维护管理的消息的子消息类型*/
		MCTRL_SUBMSG_REGION_BASE = 0x00007001,

		/*平台的消息的子消息类型*/
		PLAT_SUBMSG_REGION_BASE = 0x00008001,

		/*BSP的消息的子消息类型*/
		BSP_SUBMSG_REGION_BASE = 0x0000A001,

		/*SD采集业务收到的子消息类型*/
		OPER_VIDEO_SUBMSG_REGION_BASE = 0x0000B001,

		/*HD采集业务收到的子消息类型*/
		OPER_RGB_SUBMSG_REGION_BASE = 0x0000C001,

		/*交叉业务收到的子消息类型*/
		OPER_SW_SUBMSG_REGION_BASE = 0x0000D001,

		/*数据信号处理板的子消息类型*/
		OPER_SP_SUBMSG_REGION_BASE = 0x0000E001,

		/*调试模块子消息类型*/
		DBG_SUBMSG_REGION_BASE = 0x0000F001,

		
}SUBMSG_ID_E;



